# Generated by Django 4.2.16 on 2024-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
