# Generated by Django 4.2.16 on 2024-10-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
