# Generated by Django 4.2.16 on 2024-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_person_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
