# Generated by Django 4.2.16 on 2024-11-22 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_worker_description_worker_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wallet_balance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
