# Generated by Django 4.2.16 on 2024-11-27 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_rename_count_beds_field_all_beds_and_more'),
        ('orders', '0009_alter_order_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bed',
        ),
        migrations.AddField(
            model_name='order',
            name='beds_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='order',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garden.field'),
            preserve_default=False,
        ),
    ]
