# Generated by Django 4.2.16 on 2024-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_bed_order_beds_count_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fertilize',
            field=models.BooleanField(default=False),
        ),
    ]
