# Generated by Django 4.2.16 on 2024-09-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agronomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('days_work', models.CharField(max_length=1024)),
                ('work_schedule', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GardenBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1024)),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024)),
                ('account_number', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1024)),
                ('salary', models.IntegerField()),
                ('days_work', models.CharField(max_length=1024)),
                ('work_schedule', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=1024)),
                ('login', models.CharField(max_length=1024)),
                ('role', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=18)),
                ('agronomist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.agronomist', verbose_name='agronomist_id')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.worker', verbose_name='worker_id')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.gardenbed', verbose_name='garden_id')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('growth_conditions', models.CharField(max_length=1024)),
                ('nutrients', models.CharField(max_length=1024)),
                ('fertilizer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.fertilizer', verbose_name='fertilizer_id')),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.gardenbed', verbose_name='garden_id')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.gardenbed', verbose_name='garden_id')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.plant', verbose_name='plant_id')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.worker', verbose_name='worker_id')),
            ],
        ),
    ]
