# Generated by Django 4.2.16 on 2024-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
