# Generated by Django 4.2.16 on 2024-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_bed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='price',
        ),
        migrations.AddField(
            model_name='field',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
