# Generated by Django 4.2.16 on 2024-10-19 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_fertilizer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='growth_conditions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='nutrients',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='boost',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='landing_data',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 10, 51, 33, 167403, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
