# Generated by Django 4.2.16 on 2024-11-22 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_remove_bed_price_field_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
