# Generated by Django 4.2.16 on 2024-10-19 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_rename_growth_conditions_plant_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('growth_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=1024)),
                ('landing_data', models.DateField()),
                ('garden_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='gardenbed',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agronomist',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='boost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='gardenbed',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plot',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=1024, unique=True, validators=[django.core.validators.EmailValidator(allowlist=['mail.ru', 'gmail.com', 'yahoo.com', 'yandex.ru'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=1024, unique=True, validators=[django.core.validators.EmailValidator(allowlist=['mail.ru', 'gmail.com', 'yahoo.com', 'yandex.ru'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(regex='^+7d{10}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
