# Generated by Django 4.2.16 on 2024-10-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_availableplants_gardenbed_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableplants',
            old_name='garden_id',
            new_name='garden_num',
        ),
    ]
