# Generated by Django 4.2.16 on 2024-10-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_rename_garden_id_availableplants_garden_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableplants',
            old_name='garden_num',
            new_name='garden_id',
        ),
    ]
