# Generated by Django 4.2.16 on 2024-11-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_rename_count_beds_field_all_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='garden.field'),
        ),
    ]
