# Generated by Django 4.2.16 on 2024-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_alter_bed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
