# Generated by Django 4.2.16 on 2024-10-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('garden', '0007_rename_garden_num_availableplants_garden_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.DeleteModel(
            name='AvailablePlants',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fertilizer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='garden_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='garden_id',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='garden_id',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agronomist_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='worker_id',
        ),
        migrations.DeleteModel(
            name='Agronomist',
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='GardenBed',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='bed',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.field'),
        ),
        migrations.AddField(
            model_name='bed',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
