# Generated by Django 4.2.16 on 2024-11-28 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_field_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='all_beds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='field',
            name='count_free_beds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
