# Generated by Django 4.2.16 on 2024-10-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_person_remove_user_groups_and_more'),
        ('garden', '0008_bed_field_delete_availableplants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.person'),
        ),
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
    ]
