# Generated by Django 4.2.16 on 2024-10-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_person_phone_number'),
        ('garden', '0009_alter_bed_rented_by_alter_field_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agronomist'),
        ),
    ]
