# Generated by Django 4.2.16 on 2024-10-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_alter_field_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='owner',
        ),
        migrations.AddField(
            model_name='field',
            name='count_beds',
            field=models.IntegerField(default=0),
        ),
    ]
