# Generated by Django 4.2.16 on 2024-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_bedplant_growth_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
