# Generated by Django 4.2.16 on 2024-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedplant',
            name='is_harvested',
            field=models.BooleanField(default=False),
        ),
    ]
