# Generated by Django 4.2.16 on 2024-11-22 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_bedplant_is_harvested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
