# Generated by Django 4.2.16 on 2024-11-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedplant',
            name='growth_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
