# Generated by Django 4.2.16 on 2024-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_bedplant_growth_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
