# Generated by Django 4.2.16 on 2024-11-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_bedplant_remaining_growth_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedplant',
            name='remaining_growth_time',
        ),
    ]
