# Generated by Django 4.2.16 on 2024-10-26 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('compound', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BedPlantFertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('bed_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.bedplant')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.fertilizer')),
            ],
        ),
    ]
