# Generated by Django 4.2.16 on 2024-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        ('fertilizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedplantfertilizer',
            name='bed_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.bedplant'),
        ),
        migrations.AddField(
            model_name='bedplantfertilizer',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer.fertilizer'),
        ),
    ]
