# run on commit
name: CI
permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-commit-message:
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.get_commit_message.outputs.message }}
    steps:
    - uses: actions/checkout@v4
    - name: "Fetch commit message"
      id: get_commit_message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "::set-output name=message::$COMMIT_MESSAGE"

  check-no-ci:
    runs-on: ubuntu-latest
    needs: fetch-commit-message
    outputs:
      no_ci: ${{ steps.check_no_ci.outputs.no_ci }}
    steps:
    - name: "Check for [no_ci] in commit message"
      id: check_no_ci
      run: |
        if echo "${{ needs.fetch-commit-message.outputs.commit_message }}" | grep -iq '[no_ci]'; then
          echo "no_ci=true" >> $GITHUB_OUTPUT
        else
          echo "no_ci=false" >> $GITHUB_OUTPUT
        fi

  spellcheck:
    runs-on: ubuntu-latest
    if: "needs.check-no-ci.outputs.no_ci == 'false'"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install codespell
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell
      - name: Run Spellchecker
        run: codespell
