#
name: Create and publish a Docker images to GitHub Packages

on:
  # workflow_run:
  #   workflows: ["CI-main"]
  #   types:
  #     - completed
  # release:
  #   types: [created, published]
  # push:
  #   tags:
  #     - v*
  workflow_dispatch:
    inputs:
      type:
        description: "Release type"
        required: true
        type: choice
        options:
          - "Stable"
          - "Pre-release"
      skip_build:
        description: "Skip build/test step"
        type: boolean
        default: false
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DJANGO_SUFFIX: -django
  FRONTEND_SUFFIX: -frontend
  NGINX_SUFFIX: -nginx
  PSQL_SUFFIX: -psql

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  set-prefix:
    runs-on: ubuntu-latest
    outputs:
      PREFIX: ${{ steps.set_prefix.outputs.PREFIX }}
    steps:
      - name: Set PREFIX
        id: set_prefix
        run: |
          if [ '${{ github.event.inputs.type }}' == 'Stable' ]; then
            echo "PREFIX=" >> $GITHUB_ENV
          else
            echo "PREFIX=pre-" >> $GITHUB_ENV
          fi
          echo "PREFIX=$PREFIX" >> $GITHUB_OUTPUT

  print-conf:
    runs-on: ubuntu-latest
    needs:
      - set-prefix
    steps:
      - name: Print configuration
        run: |
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "REGISTRY: ${{ env.REGISTRY }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "DJANGO_SUFFIX: ${{ env.DJANGO_SUFFIX }}"
          echo "FRONTEND_SUFFIX: ${{ env.FRONTEND_SUFFIX }}"
          echo "NGINX_SUFFIX: ${{ env.NGINX_SUFFIX }}"
          echo "RELEASE_PREFIX: ${{ needs.set_prefix.outputs.PREFIX }}"
          echo "RELEASE_PREFIX: ${{ env.PREFIX }}"
          echo "RELEASE_PREFIX: $PREFIX"

  build-and-push-image-django:
    runs-on: ubuntu-latest
    # run if not skip
    if: ${{ !github.event.inputs.skip_build }}
    needs:
      - set-prefix
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.DJANGO_SUFFIX }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./django
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)." 
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}${{ env.DJANGO_SUFFIX }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Tag image as latest if release
        if: ${{ needs.set-prefix.outputs.PREFIX }} == ''
        run: |
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.DJANGO_SUFFIX }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.DJANGO_SUFFIX }}:latest

      - name: Tag image with latest release number
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          STRIPPED_TAG=${RELEASE_TAG#v}
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.DJANGO_SUFFIX }}:${{ needs.set-prefix.outputs.PREFIX }}$STRIPPED_TAG
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.DJANGO_SUFFIX }}:${{ needs.set-prefix.outputs.PREFIX }}$STRIPPED_TAG

  build-and-push-image-frontend:
    runs-on: ubuntu-latest
    # run if not skip
    if: ${{ !github.event.inputs.skip_build }}
    needs:
      - set-prefix
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.FRONTEND_SUFFIX }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
            context: ./frontend
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}${{ env.FRONTEND_SUFFIX }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Tag image as latest if release
        if: ${{ needs.set-prefix.outputs.PREFIX }} == ''
        run: |
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.FRONTEND_SUFFIX }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.FRONTEND_SUFFIX }}:latest

      - name: Tag image with latest release number
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          STRIPPED_TAG=${RELEASE_TAG#v}
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.FRONTEND_SUFFIX }}:${{ needs.set-prefix.outputs.PREFIX }}$STRIPPED_TAG
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.FRONTEND_SUFFIX }}:${{ needs.set-prefix.outputs.PREFIX }}$STRIPPED_TAG

  build-and-push-image-nginx:
    runs-on: ubuntu-latest
    # run if not skip
    if: ${{ !github.event.inputs.skip_build }}
    needs:
      - set-prefix
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.NGINX_SUFFIX }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
            context: ./nginx
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}${{ env.NGINX_SUFFIX }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Tag image as latest if release
        if: ${{ needs.set-prefix.outputs.PREFIX }} == ''
        run: |
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.NGINX_SUFFIX }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.NGINX_SUFFIX }}:latest

      - name: Tag image with latest release number
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          STRIPPED_TAG=${RELEASE_TAG#v}
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.NGINX_SUFFIX }}:${{ needs.set-prefix.outputs.PREFIX }}$STRIPPED_TAG
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ env.NGINX_SUFFIX }}:${{ needs.set-prefix.outputs.PREFIX }}$STRIPPED_TAG